spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopp
    username: sa
    password: thd02026
    driver-class-name: org.h2.Driver


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
# logger? ??? sql ??(??)
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6
# system.out.println? ?? sql ??(????? logger? ?? ?? ??)
